### ISSUE TITLE
how to make composer work on normal host ?

### ISSUE THREAD

**Issue by lotfiuser** [vikas5914/steam-auth#2]
![image](https://user-images.githubusercontent.com/5274016/37880472-4e833c94-3089-11e8-8cff-9a5a7f1c0f4c.png)

**Comment by vikas5914** [comment]
Do you mean sharing hosting? 

Run composer install on your pc and upload the vendor upload to your hosting.

**Comment by lotfiuser** [comment]
whats the command plz im noob

**Comment by vikas5914** [comment]
^ Start reading this: https://getcomposer.org/doc/00-intro.md
