### ISSUE TITLE
Steamid validation failure

### ISSUE THREAD

**Issue by Syntats** [vikas5914/steam-auth#6]
On line 134 of src/SteamAuth.php, $result is now always an empty string due to the requested resource now returning 403 as described by the PHP warning:

file_get_contents(https://steamcommunity.com/openid/login): failed to open stream: HTTP request failed! HTTP/1.0 403 Forbidden

Because of this, the validate() function never returns a steamid, and login validation always fails.

This came to my attention about 5 days ago when I was getting messages that registration on my site stopped working. This issue entirely prevents this script from working, for everyone.

**Comment by Rodion15** [comment]
> On line 134 of src/SteamAuth.php, $result is now always an empty string due to the requested resource now returning 403 as described by the PHP warning:
> 
> file_get_contents(https://steamcommunity.com/openid/login): failed to open stream: HTTP request failed! HTTP/1.0 403 Forbidden
> 
> Because of this, the validate() function never returns a steamid, and login validation always fails.
> 
> This came to my attention about 5 days ago when I was getting messages that registration on my site stopped working. This issue entirely prevents this script from working, for everyone.

Yes we also have a problem file_get_contents(https://steamcommunity.com/openid/login): failed to open stream: HTTP request failed! HTTP/1.0 403 Forbidden

**Comment by vikas5914** [comment]
@Syntats @Rodion15 I am not able to replicate this on my system. 

Can you guys try the following things: 

First: Use the sample code from readme and try on localhost, if you are still getting an error then remove the API key and get a new one and try. 

if still, you are getting the error: provide the PHP version.

**Comment by Rodion15** [comment]
@vikas5914 localhost(OpenServer) ok, A subdomain problem

[warn] [pid 20996] sapi_apache2.c(351): [client 77.37.228.186:36512] PHP Warning:  file_get_contents(https://steamcommunity.com/openid/login): failed to open stream: HTTP request failed! HTTP/1.0 403 Forbidden\r\n in /home/c/ce96696/rodion1/public_html/vendor/vikas5914/steam-auth/src/SteamAuth.php on line 134

PHP 7.2

**Comment by vikas5914** [comment]
@Rodion15 Can you try this link and tell if its working or not : https://steamauth.herokuapp.com/

**Comment by Rodion15** [comment]
@vikas5914 Works, seems from for hosting

**Comment by vikas5914** [comment]
Try wget http://steamcommunity.com/openid/id/xxxxxxxxxxxxxxxxx (replace x with a steam id) and check your response state in your server.

**Comment by Rodion15** [comment]
@vikas5914 ![image](https://user-images.githubusercontent.com/50318836/66110014-893cd600-e5ce-11e9-9e8f-98a0a730c571.png)
PHP Warning:  file_get_contents(http://steamcommunity.com/openid/id/76561198036039898): failed to open stream: HTTP request failed! HTTP/1.0 403 Forbidden\r\n in /home/c/ce96696/rodion1/public_html/steam.php on line 6

**Comment by Rodion15** [comment]
@vikas5914 I read another forum, the reason is that steam is blocking my ip server

**Comment by Rodion15** [comment]
@vikas5914 
![image](https://user-images.githubusercontent.com/50318836/66123740-6a990800-e5eb-11e9-9688-9fb610acbba7.png)

**Comment by vikas5914** [comment]
@Rodion15 Yeah, steam is blocking your ip address. 

Can you try with a VPN and check ?

**Comment by Rodion15** [comment]
@vikas5914 vpn everything also, it is just necessary to change IP the server but not from the client

**Comment by vikas5914** [comment]
@Rodion15 You can try with different server IP or you can try to contact steam support.

**Comment by Syntats** [comment]
Can confirm, script works fine on alternate webserver.
Looks like valve banned some IPs a couple weeks ago... not a clue as to why.
Will contact Valve. Thanks.

**Comment by vikas5914** [comment]
Thanks for confirming, I will close this issue.
